import type { Metadata } from "next"
import { GeistMono } from "geist/font/mono"
import "./globals.css"

// Configure your metadata
export const metadata: Metadata = {
  title: "Quinch",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* 
        Note: This is a server component by default (no "use client"), 
        which is recommended for layouts in Next.js 13+ 
      */}
      <body className={`${GeistMono.className} flex justify-center items-center`}>
        {children}
      </body>
    </html>
  )
}
