import type { Metadata } from "next";
import { GeistPixelSquare } from "geist/font/pixel";
import "./globals.css";
import NavBar from "@/components/navbar";
import Noise from "@/components/noise";

export const metadata: Metadata = {
  title: "Cyril James - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistPixelSquare.className} antialiased tracking-wide overflow-hidden`}
      >
        <NavBar />
        {children}
        <Noise />
      </body>
    </html>
  );
}
