import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react'

const art = () => {
  return (
		<main>
      <Head>
        <title>Quinch.Art</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.nav}>
        <div className="flex space-x-8 items-center m-4">
          <div>
            <h1 className="text-2xl">QUINCH.ART</h1>
          </div>
          <div className="flex space-x-5">
            <a className="text-1xl" href="/">Home</a>
            <a className="text-1xl" href="/art">Art</a>
            <a className="text-1xl" href="/commision">Commision</a>
          </div>
        </div>
      </nav>
      <section className={styles.main}>
        <h1 className={styles.title}>
          ART
        </h1>
      </section>
      <footer className={styles.footer}>
        © 2022 Quinch Art
      </footer>
    </main>
  )
}

export default art