import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Cyril James De Guzman</title>
        <link rel="icon" href="/QuinchLogo.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <section className='placeholder-section'>
          <div className='wait'>
            <Image src="/QuinchY.gif" width={200} height={200}/>
            <h1>. . .</h1>
          </div>
        </section>
      </main>
    </>
  )
}