import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Cyril James De Guzman</title>
        <link rel="icon" href="/QuinchLogo.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className='main'>
        <section className='introduction-section'>
          <div className='introduction'>
            <h1 className='hello'>Hello,</h1>
            <h1 className='name'>I'm Cyril James De Guzman</h1>
            <h1 className='job'>A Software Developer</h1>
          </div>
          <div className='quinch-pixel-profile'>
            <Image src="/QuinchPixelProfile.svg" width={350} height={350}/>
          </div>
        </section>
        <section className='placeholder-section'>
          <div className='wait'>
            <Image src="/QuinchY.gif" width={200} height={200}/>
            <h1><span className="dot dot-1">.</span> <span className="dot dot-2">.</span> <span className="dot dot-3">.</span></h1>
          </div>
        </section>
      </main>
    </>
  )
}